plugins {
    id 'com.android.application'
}

android {
    namespace 'nonroot.dtinh.mtzimporter'
    compileSdk 35

    defaultConfig {
        applicationId 'nonroot.dtinh.mtzimporter'
        minSdk 30
        targetSdk 35
        versionCode 10000
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation files('libs/api-12.2.0.aar')
    implementation files('libs/provider-12.2.0.aar')
    implementation files('libs/aidl-12.2.0.aar')
    implementation files('libs/shared-12.2.0.aar')
    compileOnly files('libs/annotation-1.3.0.jar')
}
