plugins {
    id 'com.android.application'
}

android {
    namespace 'root.dtinh.mtzimporter'
    compileSdk 35

    defaultConfig {
        applicationId 'root.dtinh.mtzimporter'
        minSdk 30
        targetSdk 35
        versionCode 10000
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
